// compass-js/src/components/table-of-contents.jsx
"use client";

import { clsx } from "clsx";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

function useTableOfContents(contentId) {
  let [headings, setHeadings] = useState([]);
  let pathname = usePathname();

  useEffect(() => {
    let root = document.getElementById(contentId);
    if (!root) return;

    // eslint-disable-next-line react-hooks/set-state-in-effect
    setHeadings(
      Array.from(root.querySelectorAll("h2, h3")).map((heading) => ({
        id: heading.id,
        text: heading.textContent || "",
        level: parseInt(heading.tagName[1]),
        active: false,
      })),
    );

    let contentElements = new Map();
    let currentHeadingId = null;

    Array.from(root.children).forEach((element) => {
      if (
        element.id &&
        (element.tagName === "H2" || element.tagName === "H3")
      ) {
        currentHeadingId = element.id;
      }
      if (!currentHeadingId) return;
      contentElements.set(element, currentHeadingId);
    });

    let visibleElements = new Set();

    let observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            visibleElements.add(entry.target);
          } else {
            visibleElements.delete(entry.target);
          }
        });

        let firstVisibleContentElement = Array.from(
          contentElements.entries(),
        ).find(([element]) => visibleElements.has(element));

        setHeadings((current) =>
          current.map((heading) => ({
            ...heading,
            active: heading.id === firstVisibleContentElement?.[1],
          })),
        );
      },
      {
        rootMargin: `-${getComputedStyle(document.documentElement).scrollPaddingTop} 0px 0px`,
      },
    );

    Array.from(contentElements.keys()).forEach((element) =>
      observer.observe(element),
    );

    return () => observer.disconnect();
  }, [pathname, contentId]);

  return headings;
}

export default function TableOfContents({ contentId }) {
  let headings = useTableOfContents(contentId);

  return (
    <nav className="sticky top-16">
      <h2 className="text-sm/6 font-semibold text-gray-950 dark:text-white">
        On this page
      </h2>
      <ul className="mt-3 flex flex-col gap-3 border-l border-gray-950/10 text-sm/6 text-gray-700 dark:border-white/10 dark:text-gray-400">
        {headings.map((heading) => (
          <li
            key={heading.id}
            className={clsx(
              "-ml-px border-l border-transparent pl-4",
              "hover:text-gray-950 hover:not-has-aria-[current=location]:border-gray-400 dark:hover:text-white",
              "has-aria-[current=location]:border-gray-950 dark:has-aria-[current=location]:border-white",
            )}
          >
            <a
              href={`#${heading.id}`}
              aria-current={heading.active ? "location" : undefined}
              className={clsx(
                heading.level === 3 && "pl-4",
                "block aria-[current=location]:font-medium aria-[current=location]:text-gray-950 dark:aria-[current=location]:text-white",
              )}
            >
              {heading.text}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
}

// voyager/src/lib/components/TableOfContents.svelte
<script>
	let { contentEl } = $props();

	let headings = $state([]);
	let activeId = $state('');

	$effect(() => {
		if (!contentEl) return;
		const found = Array.from(contentEl.querySelectorAll('h2, h3'))
			.filter((h) => h.id)
			.map((h) => ({
				id: h.id,
				text: h.textContent.trim(),
				level: h.tagName === 'H2' ? 2 : 3
			}));
		headings = found;

		if (found.length === 0) return;
		const observer = new IntersectionObserver(
			(entries) => {
				const visible = entries.filter((e) => e.isIntersecting);
				if (visible.length > 0) activeId = visible[0].target.id;
			},
			{ rootMargin: '-80px 0px -70% 0px', threshold: 0 }
		);
		found.forEach(({ id }) => {
			const el = document.getElementById(id);
			if (el) observer.observe(el);
		});
		return () => observer.disconnect();
	});
</script>

{#if headings.length > 0}
	<nav aria-label="On this page">
		<h2 class="text-xs font-semibold tracking-wider uppercase text-ink">On this page</h2>
		<ul class="mt-3 flex flex-col gap-2 border-l border-bone-200 text-sm text-ink-2">
			{#each headings as h (h.id)}
				<li
					class="-ml-px border-l border-transparent pl-3 {activeId === h.id
						? 'border-ink'
						: ''}"
				>
					<a
						href={`#${h.id}`}
						aria-current={activeId === h.id ? 'location' : undefined}
						class="block {h.level === 3
							? 'pl-3'
							: ''} hover:text-ink {activeId === h.id ? 'text-ink font-medium' : ''}"
					>
						{h.text}
					</a>
				</li>
			{/each}
		</ul>
	</nav>
{/if}

<style>
	nav {
		font-size: 0.8125rem;
	}
</style>
